INSERT INTO USERS(USERNAME, PASSWORD, ENABLED) VALUES ('admin', '$2y$12$UUCuH9DNg33DX90lYsN/neQ/ujvbF/ktSq5Levffl5OO8wHPY5NQi', TRUE);
INSERT INTO USERS(USERNAME, PASSWORD, ENABLED) VALUES ('doe',   '$2a$04$X0QnO08OXDd2fWQY.YDAyed49z8UnhFXg/yMAVFsBddM18g8FxXza', TRUE);
INSERT INTO USERS(USERNAME, PASSWORD, ENABLED) VALUES ('bau',   '$2a$04$p8k81iEseArTEBzxLFcW9enlwM8Q58PwAEHc68xepIWNIp4zspnh2', TRUE);
INSERT INTO USERS(USERNAME, PASSWORD, ENABLED) VALUES ('ciao',   '$2y$12$DUGWTsBuI5jEEnthu7lBmuNQwZd29rpbnG/9jWNIt1plOpZx1rk6C', TRUE);
INSERT INTO AUTHORITIES(USERNAME, AUTHORITY) VALUES ('admin', 'ROLE_ADMIN');
INSERT INTO AUTHORITIES(USERNAME, AUTHORITY) VALUES ('doe', 'ROLE_USER,ROLE_ADMIN');
INSERT INTO AUTHORITIES(USERNAME, AUTHORITY) VALUES ('bau', 'ROLE_USER');
INSERT INTO AUTHORITIES(USERNAME, AUTHORITY) VALUES ('ciao', 'ROLE_VIEWER');
