INSERT INTO USERS(USERNAME, PASSWORD, ENABLED) VALUES ('admin', '$2a$08$YN2y9ehNoknkvyPn5iVNEeb8qnCO5VDKs7FkmoM8hQjt2IZh/ACza', TRUE);
INSERT INTO USERS(USERNAME, PASSWORD, ENABLED) VALUES ('pippo', '$2a$08$YN2y9ehNoknkvyPn5iVNEeb8qnCO5VDKs7FkmoM8hQjt2IZh/ACza', TRUE);
INSERT INTO USERS(USERNAME, PASSWORD, ENABLED) VALUES ('pippo2', '$2a$08$YN2y9ehNoknkvyPn5iVNEeb8qnCO5VDKs7FkmoM8hQjt2IZh/ACza', TRUE);
INSERT INTO USERS(USERNAME, PASSWORD, ENABLED) VALUES ('ciao',  '$2a$08$YN2y9ehNoknkvyPn5iVNEeb8qnCO5VDKs7FkmoM8hQjt2IZh/ACza', TRUE);
INSERT INTO AUTHORITIES(USERNAME, AUTHORITY) VALUES ('admin', 'ROLE_ADMIN');
INSERT INTO AUTHORITIES(USERNAME, AUTHORITY) VALUES ('pippo', 'ROLE_USER');
INSERT INTO AUTHORITIES(USERNAME, AUTHORITY) VALUES ('pippo2', 'ROLE_USER');
INSERT INTO AUTHORITIES(USERNAME, AUTHORITY) VALUES ('ciao',  'ROLE_GUEST');
INSERT INTO test(nome, cognome,eta) VALUES ('nic',  'vio', 40);
INSERT INTO test(nome, cognome,eta) VALUES ('nic1',  'vio1', 41);
INSERT INTO test(nome, cognome,eta) VALUES ('nic2',  'vio2', 42);
INSERT INTO test(nome, cognome,eta) VALUES ('nic3',  'vio3', 43);
INSERT INTO test(nome, cognome,eta) VALUES ('nic4',  'vio4', 43);
INSERT INTO test(nome, cognome,eta) VALUES ('nic5',  'vio5', 43);
INSERT INTO test(nome, cognome,eta) VALUES ('nic6',  'vio6', 43);
INSERT INTO test(nome, cognome,eta) VALUES ('nic7',  'vio7', 43);
INSERT INTO test(nome, cognome,eta) VALUES ('nic8',  'vio8', 43);
