INSERT INTO USERS(USERNAME, PASSWORD, ENABLED) VALUES ('admin', '$2a$08$YN2y9ehNoknkvyPn5iVNEeb8qnCO5VDKs7FkmoM8hQjt2IZh/ACza', TRUE);
INSERT INTO USERS(USERNAME, PASSWORD, ENABLED) VALUES ('pippo', '$2a$08$YN2y9ehNoknkvyPn5iVNEeb8qnCO5VDKs7FkmoM8hQjt2IZh/ACza', TRUE);
INSERT INTO USERS(USERNAME, PASSWORD, ENABLED) VALUES ('ciao',  '$2a$08$YN2y9ehNoknkvyPn5iVNEeb8qnCO5VDKs7FkmoM8hQjt2IZh/ACza', TRUE);
INSERT INTO AUTHORITIES(USERNAME, AUTHORITY) VALUES ('admin', 'ROLE_ADMIN');
INSERT INTO AUTHORITIES(USERNAME, AUTHORITY) VALUES ('pippo', 'ROLE_USER');
INSERT INTO AUTHORITIES(USERNAME, AUTHORITY) VALUES ('ciao',  'ROLE_GUEST');